name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main

env:
  WATCH_LIST_TABLE: binance.watch_list
  OUTPUT_TABLE: binance.asset_info

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GCloud Auth
        uses: google-github-actions/auth@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Deploy Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: aggregate-binance-data
          description: aggregate price data from binance
          region: asia-northeast1
          entry_point: execute
          runtime: python310
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/${{ secrets.GCP_PROJECT }}/topics/aggregate-crypto-data
          env_vars: "BIGQUERY_WATCH_LIST_TABLE=${{ env.WATCH_LIST_TABLE }},BIGQUERY_OUTPUT_TABLE=${{ env.OUTPUT_TABLE }}"
          secret_environment_variables: "BINANCE_API_KEY=projects/${{ secrets.GCP_PROJECT }}/secrets/binance-api-key,BINANCE_API_SECRET=projects/${{ secrets.GCP_PROJECT }}/secrets/binance-api-secret"
